# Generated by Django 5.2.8 on 2026-02-05 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_producto_destacado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('tipo', models.CharField(choices=[('calzado', 'Numérico (Calzado)'), ('ropa', 'Letras (Indumentaria)')], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stock',
        ),
        migrations.CreateModel(
            name='VarianteProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='catalogo.producto')),
                ('talla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.talla')),
            ],
            options={
                'unique_together': {('producto', 'talla')},
            },
        ),
    ]
