# Generated by Django 5.2.8 on 2026-02-05 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_talla_remove_producto_stock_varianteproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talla',
            name='tipo',
            field=models.CharField(choices=[('calzado', 'Numérico (Calzado)'), ('ropa', 'Letras (Indumentaria)'), ('unico', 'Talla Única / Accesorios')], max_length=20),
        ),
    ]
