# Generated by Django 5.2.8 on 2026-02-05 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_alter_talla_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempedido',
            name='producto',
        ),
        migrations.AddField(
            model_name='itempedido',
            name='variante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_pedido', to='catalogo.varianteproducto'),
        ),
    ]
