# Generated by Django 5.2.8 on 2026-03-14 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_remove_itempedido_producto_itempedido_variante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='ItemPedido',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
