# Generated by Django 5.2.8 on 2026-03-14 23:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0006_remove_pedido_usuario_delete_itempedido_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Pago'), ('preparando', 'Preparando Pedido'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('nombre_completo', models.CharField(help_text='Nombre de quien recibe', max_length=150)),
                ('telefono', models.CharField(help_text='Celular para la transportadora', max_length=20)),
                ('ciudad', models.CharField(default='Bogotá DC', max_length=100)),
                ('direccion', models.CharField(help_text='Dirección principal', max_length=250)),
                ('detalles_direccion', models.CharField(blank=True, help_text='Apto, Torre, Barrio, Conjunto', max_length=250, null=True)),
                ('notas_pedido', models.TextField(blank=True, help_text='Ej: Dejar en portería, timbre dañado', null=True)),
                ('metodo_pago', models.CharField(choices=[('contraentrega', 'Pago a Contraentrega'), ('debito', 'Tarjeta de débito'), ('credito', 'Tarjeta de crédito'), ('pse', 'PSE')], max_length=20)),
                ('id_transaccion', models.CharField(blank=True, help_text='ID de Mercado Pago si aplica', max_length=100, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('precio_historico', models.DecimalField(decimal_places=2, max_digits=10)),
                ('variante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.varianteproducto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pedidos.pedido')),
            ],
        ),
    ]
